AWSTemplateFormatVersion: '2010-09-09'
Description: 'Creating an EC2 Instance along with a SecurityGroup'
Resources:
  Server1:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0a91cd140a1fc148a
      InstanceType: t2.micro
      KeyName: chetan-labs
      SecurityGroups:
      - Ref: Server1SecurityGroup
  Server1SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "Enable HTTP access via port 80 + SSH access"
      SecurityGroupIngress:
      - CidrIp: 0.0.0.0/0
        FromPort: 80
        IpProtocol: tcp
        ToPort: 80
      - CidrIp: 0.0.0.0/0
        FromPort: 22
        IpProtocol: tcp
        ToPort: 22
Outputs:
  PublicIP:
    Description: EC2 public IP
    Value: !GetAtt Server1.PublicIp
