AWSTemplateFormatVersion: '2010-09-09'
Description: 'EC2 Template'
Parameters:
  SshKey:
    ConstraintDescription: must be the name of an existing EC2 KeyPair.
    Description: Name of an existing EC2 KeyPair to enable SSH access to the instances
    Type: AWS::EC2::KeyPair::KeyName
  SSHLocation:
    AllowedPattern: (\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})
    ConstraintDescription: must be a valid IP CIDR range of the form x.x.x.x/x.
    Default: 0.0.0.0/0
    Description: The IP address range that can be used to SSH to the EC2 instances
    MaxLength: '18'
    MinLength: '9'
    Type: String
Resources:
  Server1:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0a91cd140a1fc148a
      InstanceType: t2.micro
      KeyName:
        Ref: SshKey
      SecurityGroups:
      - Ref: Server1SecurityGroup
  Server1SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "Enable HTTP access via port 80 + SSH access"
      SecurityGroupIngress:
      - CidrIp: 0.0.0.0/0
        FromPort: 80
        IpProtocol: tcp
        ToPort: 80
      - CidrIp: !Ref SSHLocation
        FromPort: 22
        IpProtocol: tcp
        ToPort: 22
Outputs:
  PublicIP:
    Description: EC2 public IP
    Value: !GetAtt Server1.PublicIp
